name: Linting

on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  java-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Java Checkstyle
        uses: Justintime50/java-checkstyle-action@v1
        with:
          directory: /src/main/java
          # The name of the style suite to be used, either 'sun' or 'google'.
          # Default is shown.
          style_suite: google
